# Generated by Django 2.2 on 2020-11-21 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materi',
            fields=[
                ('id', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=90, null=True)),
                ('level', models.CharField(max_length=90, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Peserta',
            fields=[
                ('id', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=90, null=True)),
                ('gender', models.CharField(max_length=90, null=True)),
                ('age', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='DaftarPeserta',
            fields=[
                ('id', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('materi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.Materi')),
                ('peserta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.Peserta')),
            ],
        ),
    ]
